# Generated by Django 3.2.9 on 2025-02-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.AddField(
            model_name='course',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='app.course'),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklog', to='app.course'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='app.classes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app.classes'),
        ),
    ]
