# Generated by Django 3.2.9 on 2025-02-26 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250221_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='week',
        ),
        migrations.AlterField(
            model_name='course',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='app.classes', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
    ]
