# Generated by Django 3.2.9 on 2025-02-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250226_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='option_username',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='check_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
